### ISSUE TITLE
function to generate url from key and params

### ISSUE THREAD

**Issue by foxdonut** [kevindurb/router#3] opened 2018-11-28 22:09 UTC
Nice router, small and simple!

One functionality that I think would help with applications as they grow bigger, is being able to avoid hardcoding URLs. It's nice being able to add routes with a string identifier (constant), so this could be used to generate the URL by key instead of hardcoding:

```javascript
app.add('/people/:id', 'PERSON');

app.toUrl('PERSON', { id: 42 }); // returns "/people/42"
```

What do you think?

Thanks!

**Comment by tracker1** [comment] 2018-11-28 23:36
See #2, I just called it `compose` to couple with a `resolve` method.

**Comment by kevindurb** [comment] 2018-12-01 19:04
Im gonna close this as a dupe of #2 like @tracker1 said. I see theres more of a want for this. I'll put this as next on my list, but of course im open to pull requests :)

**Closed by kevindurb** 2018-12-01 19:04 UTC
